# Generated by Django 5.2.4 on 2025-08-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_shippingaddress_shipping_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'در انتظار پرداخت'), ('Processing', 'درحال پردازش'), ('Shipped', 'ارسال شده به پست'), ('Delivered', 'تحویل داده شده')], default='Pending', max_length=24),
        ),
    ]
