# Generated by Django 5.2.4 on 2025-07-29 19:56

import datetime
import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_star_alter_order_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 7, 29, 23, 26, 1, 443963)),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name=django.contrib.auth.models.User)),
                ('phone', models.CharField(blank=True, max_length=24)),
                ('adress1', models.CharField(blank=True, max_length=240)),
                ('adress2', models.CharField(blank=True, max_length=240)),
                ('city', models.CharField(blank=True, max_length=24)),
                ('state', models.CharField(blank=True, max_length=24)),
                ('zipcode', models.CharField(blank=True, max_length=24)),
                ('country', models.CharField(blank=True, max_length=24)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
